services:
  api_registry:
    build: .
    container_name: api_registry
    env_file: .env
    ports:
      - "9101:9101"
    volumes:
      - ".:/root"
      - "/tmp/out:/tmp/out"
    healthcheck:
      test: 
        ["CMD", "curl", "-fsS", "http://localhost:${PORT}/ping", ">", "/dev/null"]
      interval: 30s
      timeout: 5s
      retries: 3