name: Test

on:
  workflow_dispatch:
    inputs:
      APP_NAME:
        description: "App name"
        required: false
        default: "myapp"
      PORT:
        description: "Port"
        required: false
        default: "8000"
      DB_URL:
        description: "Database URL"
        required: false
        default: "sqlite:///db.sqlite3"
      DEBUG:
        description: "Debug"
        required: false
        default: "0"
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ${{ secrets.APP_NAME || github.event.inputs.APP_NAME || 'myapp' }}
      PORT: ${{ secrets.PORT || github.event.inputs.PORT || '8000' }}
      DB_URL: ${{ secrets.DB_URL || github.event.inputs.DB_URL || 'sqlite:///db.sqlite3' }}
      DEBUG: ${{ secrets.DEBUG || github.event.inputs.DEBUG || '0' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: ndeloof/install-compose-action@v0.0.1

      - name: Set execute permission for deploy.sh
        run: chmod +x ./deploy.sh

      - name: Generate .env from .env.example (inputs/secrets/defaults)
        run: |
          cp .env.example .env
          sed -i "s|@@APP_NAME@@|${{ secrets.APP_NAME || github.event.inputs.APP_NAME || 'myapp' }}|g" .env
          sed -i "s|@@PORT@@|${{ secrets.PORT || github.event.inputs.PORT || '8000' }}|g" .env
          sed -i "s|@@DB_URL@@|${{ secrets.DB_URL || github.event.inputs.DB_URL || 'sqlite:///db.sqlite3' }}|g" .env
          sed -i "s|@@DEBUG@@|${{ secrets.DEBUG || github.event.inputs.DEBUG || '0' }}|g" .env

      - name: Run deploy.sh with test param
        env:
          PORT: ${{ secrets.PORT || github.event.inputs.PORT }}
        run: ./deploy.sh test | tee test-output.log

      - name: Add test output to summary
        if: always()
        run: |
          echo '### ðŸ”¥ Test.sh Output' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          cat test-output.log >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
