name: Test

on:
  workflow_dispatch:
    inputs:
      APP_NAME:
        description: "App name"
        required: false
        default: "myapp"
      PORT:
        description: "Port"
        required: false
        default: "8000"
      DB_URL:
        description: "Database URL"
        required: false
        default: "sqlite:///db.sqlite3"
      DEBUG:
        description: "Debug"
        required: false
        default: "0"
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        uses: ndeloof/install-compose-action@v1

      - name: Set execute permission for deploy.sh
        run: chmod +x ./deploy.sh

      - name: Generate .env from .env.example (inputs/secrets)
        run: |
          cp .env.example .env
          sed -i "s|@@APP_NAME@@|${{ github.event.inputs.APP_NAME || secrets.APP_NAME }}|g" .env
          sed -i "s|@@PORT@@|${{ github.event.inputs.PORT || secrets.PORT }}|g" .env
          sed -i "s|@@DB_URL@@|${{ github.event.inputs.DB_URL || secrets.DB_URL }}|g" .env
          sed -i "s|@@DEBUG@@|${{ github.event.inputs.DEBUG || secrets.DEBUG }}|g" .env

      - name: Run deploy.sh with test param
        run: ./deploy.sh test
